name: Validate pull request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - 'force-app/**'
  push:
    branches:
      - main

jobs:
  CodeScan: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Cache files 
        uses: actions/cache@v4
        with: 
            path: | 
                ~/.sonar 
            key: ${{ runner.os }}-sonar 
            restore-keys: ${{ runner.os }}-sonar 
      - name: Run Codescan On Push 
        if: github.event_name == 'push' 
        uses: codescan-io/codescan-scanner-action@1.6
        with: 
          organization: ‘githubrepos’
          projectKey: ‘Evitaliysergeychik-CodeScanActions’ 
          login: ${{ secrets.codescan_token }} 
          generateSarifFile: true 
          failOnRedQualityGate: true 
      - name: Run Codescan On PR 
        if: github.event_name == 'pull_request' 
        uses: codescan-io/codescan-scanner-action@1.6
        with: 
          organization: ‘githubrepos’ 
          projectKey: ‘vitaliysergeychik-CodeScanActions’ 
          login: ${{ secrets.codescan_token }} 
          scanChangedFilesOnly: true 
          generateSarifFile: true 
          failOnRedQualityGate: true 
          args: | 
            sonar.pullrequest.branch=${{github.head_ref}} 
            sonar.pullrequest.base=${{github.base_ref}} 
            sonar.pullrequest.key=${{github.event.number}} 
  validate-deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Authenticate using SFDX_AUTH_URL'
        run: | 
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u

      - name: 'Validate'
        run: |
          sf project deploy validate --manifest package.xml -l RunLocalTests -w 30          
